export const guitars = [
  {
    id: 'SO757575',
    name: 'Честер Bass',
    type: 'электрогитара',
    popularity: 15,
    stringNumber: 7,
    price: 17500,
    img: 'img/guitar-1',
  },
  {
    id: 'TK129049',
    name: 'СURT Z300',
    type: 'электрогитара',
    popularity: 9,
    stringNumber: 7,
    price: 29500,
    img: 'img/guitar-2',
  },
  {
    id: 'RO111111',
    name: 'Roman LX',
    type: 'укулеле',
    popularity: 21,
    stringNumber: 4,
    price: 6800,
    img: 'img/guitar-3',
  },
  {
    id: 'TK436457',
    name: 'СURT T300',
    type: 'электрогитара',
    popularity: 15,
    stringNumber: 6,
    price: 30000,
    img: 'img/guitar-4',
  },
  {
    id: 'DI192138',
    name: 'Dania Super',
    type: 'акустическая гитара',
    popularity: 5,
    stringNumber: 7,
    price: 3500,
    img: 'img/guitar-5',
  },
  {
    id: 'SO934345',
    name: 'Честер WX ',
    type: 'электрогитара',
    popularity: 17,
    stringNumber: 6,
    price: 15300,
    img: 'img/guitar-1',
  },
  {
    id: 'DI082347',
    name: 'Dania VX',
    type: 'укулеле',
    popularity: 5,
    stringNumber: 4,
    price: 2200,
    img: 'img/guitar-3',
  },
  {
    id: 'SO135646',
    name: 'Честер Plus',
    type: 'электрогитара',
    popularity: 27,
    stringNumber: 4,
    price: 30000,
    img: 'img/guitar-6',
  },
  {
    id: 'VO154751',
    name: 'Виолана 300',
    type: 'акустическая гитара',
    popularity: 3,
    stringNumber: 7,
    price: 1700,
    img: 'img/guitar-5',
  },
  {
    id: 'SO757575',
    name: 'Честер Bassss',
    type: 'электрогитара',
    popularity: 15,
    stringNumber: 7,
    price: 17500,
    img: 'img/guitar-1',
  },
  {
    id: 'TK129049',
    name: 'СURT Z300',
    type: 'электрогитара',
    popularity: 9,
    stringNumber: 7,
    price: 29500,
    img: 'img/guitar-2',
  },
  {
    id: 'RO111111',
    name: 'Roman LX',
    type: 'укулеле',
    popularity: 21,
    stringNumber: 4,
    price: 6800,
    img: 'img/guitar-3',
  },
  {
    id: 'TK436457',
    name: 'СURT T300',
    type: 'электрогитара',
    popularity: 15,
    stringNumber: 6,
    price: 30000,
    img: 'img/guitar-4',
  },
  {
    id: 'DI192138',
    name: 'Dania Super',
    type: 'акустическая гитара',
    popularity: 5,
    stringNumber: 7,
    price: 3500,
    img: 'img/guitar-5',
  },
  {
    id: 'SO934345',
    name: 'Честер WX ',
    type: 'электрогитара',
    popularity: 17,
    stringNumber: 6,
    price: 15300,
    img: 'img/guitar-1',
  },
  {
    id: 'DI082347',
    name: 'Dania VX',
    type: 'укулеле',
    popularity: 5,
    stringNumber: 4,
    price: 2200,
    img: 'img/guitar-3',
  },
  {
    id: 'SO135646',
    name: 'Честер Plus',
    type: 'электрогитара',
    popularity: 27,
    stringNumber: 4,
    price: 30000,
    img: 'img/guitar-6',
  },
  {
    id: 'VO154751',
    name: 'Виолана 300',
    type: 'акустическая гитара',
    popularity: 3,
    stringNumber: 7,
    price: 1700,
    img: 'img/guitar-5',
  },
  {
    id: 'SO757575',
    name: 'Честер Bass',
    type: 'электрогитара',
    popularity: 15,
    stringNumber: 7,
    price: 17500,
    img: 'img/guitar-1',
  },
  {
    id: 'TK129049',
    name: 'СURT Z300',
    type: 'электрогитара',
    popularity: 9,
    stringNumber: 7,
    price: 29500,
    img: 'img/guitar-2',
  },
  {
    id: 'RO111111',
    name: 'Roman LX',
    type: 'укулеле',
    popularity: 21,
    stringNumber: 4,
    price: 6800,
    img: 'img/guitar-3',
  },
  {
    id: 'TK436457',
    name: 'СURT T300',
    type: 'электрогитара',
    popularity: 15,
    stringNumber: 6,
    price: 30000,
    img: 'img/guitar-4',
  },
  {
    id: 'DI192138',
    name: 'Dania Super',
    type: 'акустическая гитара',
    popularity: 5,
    stringNumber: 7,
    price: 3500,
    img: 'img/guitar-5',
  },
  {
    id: 'SO934345',
    name: 'Честер WX ',
    type: 'электрогитара',
    popularity: 17,
    stringNumber: 6,
    price: 15300,
    img: 'img/guitar-1',
  },
  {
    id: 'DI082347',
    name: 'Dania VX',
    type: 'укулеле',
    popularity: 5,
    stringNumber: 4,
    price: 2200,
    img: 'img/guitar-3',
  },
  {
    id: 'SO135646',
    name: 'Честер Plus',
    type: 'электрогитара',
    popularity: 27,
    stringNumber: 4,
    price: 30000,
    img: 'img/guitar-6',
  },
  {
    id: 'VO154751',
    name: 'Виолана 300',
    type: 'акустическая гитара',
    popularity: 3,
    stringNumber: 7,
    price: 1700,
    img: 'img/guitar-5',
  },
  {
    id: 'SO757575',
    name: 'Честер Bass',
    type: 'электрогитара',
    popularity: 15,
    stringNumber: 7,
    price: 17500,
    img: 'img/guitar-1',
  },
  {
    id: 'TK129049',
    name: 'СURT Z300',
    type: 'электрогитара',
    popularity: 9,
    stringNumber: 7,
    price: 29500,
    img: 'img/guitar-2',
  },
  {
    id: 'RO111111',
    name: 'Roman LX',
    type: 'укулеле',
    popularity: 21,
    stringNumber: 4,
    price: 6800,
    img: 'img/guitar-3',
  },
  {
    id: 'TK436457',
    name: 'СURT T300',
    type: 'электрогитара',
    popularity: 15,
    stringNumber: 6,
    price: 30000,
    img: 'img/guitar-4',
  },
  {
    id: 'DI192138',
    name: 'Dania Super',
    type: 'акустическая гитара',
    popularity: 5,
    stringNumber: 7,
    price: 3500,
    img: 'img/guitar-5',
  },
  {
    id: 'SO934345',
    name: 'Честер WX ',
    type: 'электрогитара',
    popularity: 17,
    stringNumber: 6,
    price: 15300,
    img: 'img/guitar-1',
  },
  {
    id: 'DI082347',
    name: 'Dania VX',
    type: 'укулеле',
    popularity: 5,
    stringNumber: 4,
    price: 2200,
    img: 'img/guitar-3',
  },
  {
    id: 'SO135646',
    name: 'Честер Plus',
    type: 'электрогитара',
    popularity: 27,
    stringNumber: 4,
    price: 30000,
    img: 'img/guitar-6',
  },
  {
    id: 'VO154751',
    name: 'Виолана 300',
    type: 'акустическая гитара',
    popularity: 3,
    stringNumber: 7,
    price: 1700,
    img: 'img/guitar-5',
  },
  {
    id: 'SO757575',
    name: 'Честер Bass',
    type: 'электрогитара',
    popularity: 15,
    stringNumber: 7,
    price: 17500,
    img: 'img/guitar-1',
  },
  {
    id: 'TK129049',
    name: 'СURT Z300',
    type: 'электрогитара',
    popularity: 9,
    stringNumber: 7,
    price: 29500,
    img: 'img/guitar-2',
  },
  {
    id: 'RO111111',
    name: 'Roman LX',
    type: 'укулеле',
    popularity: 21,
    stringNumber: 4,
    price: 6800,
    img: 'img/guitar-3',
  },
  {
    id: 'TK436457',
    name: 'СURT T300',
    type: 'электрогитара',
    popularity: 15,
    stringNumber: 6,
    price: 30000,
    img: 'img/guitar-4',
  },
  {
    id: 'DI192138',
    name: 'Dania Super',
    type: 'акустическая гитара',
    popularity: 5,
    stringNumber: 7,
    price: 3500,
    img: 'img/guitar-5',
  },
  {
    id: 'SO934345',
    name: 'Честер WX ',
    type: 'электрогитара',
    popularity: 17,
    stringNumber: 6,
    price: 15300,
    img: 'img/guitar-1',
  },
  {
    id: 'DI082347',
    name: 'Dania VX',
    type: 'укулеле',
    popularity: 5,
    stringNumber: 4,
    price: 2200,
    img: 'img/guitar-3',
  },
  {
    id: 'SO135646',
    name: 'Честер Plus',
    type: 'электрогитара',
    popularity: 27,
    stringNumber: 4,
    price: 30000,
    img: 'img/guitar-6',
  },
  {
    id: 'VO154751',
    name: 'Виолана 300',
    type: 'акустическая гитара',
    popularity: 3,
    stringNumber: 7,
    price: 1700,
    img: 'img/guitar-5',
  },
  {
    id: 'SO757575',
    name: 'Честер Bass',
    type: 'электрогитара',
    popularity: 15,
    stringNumber: 7,
    price: 17500,
    img: 'img/guitar-1',
  },
  {
    id: 'TK129049',
    name: 'СURT Z300',
    type: 'электрогитара',
    popularity: 9,
    stringNumber: 7,
    price: 29500,
    img: 'img/guitar-2',
  },
  {
    id: 'RO111111',
    name: 'Roman LX',
    type: 'укулеле',
    popularity: 21,
    stringNumber: 4,
    price: 6800,
    img: 'img/guitar-3',
  },
  {
    id: 'TK436457',
    name: 'СURT T300',
    type: 'электрогитара',
    popularity: 15,
    stringNumber: 6,
    price: 30000,
    img: 'img/guitar-4',
  },
  {
    id: 'DI192138',
    name: 'Dania Super',
    type: 'акустическая гитара',
    popularity: 5,
    stringNumber: 7,
    price: 3500,
    img: 'img/guitar-5',
  },
  {
    id: 'SO934345',
    name: 'Честер WX ',
    type: 'электрогитара',
    popularity: 17,
    stringNumber: 6,
    price: 15300,
    img: 'img/guitar-1',
  },
  {
    id: 'DI082347',
    name: 'Dania VX',
    type: 'укулеле',
    popularity: 5,
    stringNumber: 4,
    price: 2200,
    img: 'img/guitar-3',
  },
  {
    id: 'SO135646',
    name: 'Честер Plus',
    type: 'электрогитара',
    popularity: 27,
    stringNumber: 4,
    price: 30000,
    img: 'img/guitar-6',
  },
  {
    id: 'VO154751',
    name: 'Виолана 300',
    type: 'акустическая гитара',
    popularity: 3,
    stringNumber: 7,
    price: 1700,
    img: 'img/guitar-5',
  },
  {
    id: 'SO757575',
    name: 'Честер Bass',
    type: 'электрогитара',
    popularity: 15,
    stringNumber: 7,
    price: 17500,
    img: 'img/guitar-1',
  },
  {
    id: 'TK129049',
    name: 'СURT Z300',
    type: 'электрогитара',
    popularity: 9,
    stringNumber: 7,
    price: 29500,
    img: 'img/guitar-2',
  },
  {
    id: 'RO111111',
    name: 'Roman LX',
    type: 'укулеле',
    popularity: 21,
    stringNumber: 4,
    price: 6800,
    img: 'img/guitar-3',
  },
  {
    id: 'TK436457',
    name: 'СURT T300',
    type: 'электрогитара',
    popularity: 15,
    stringNumber: 6,
    price: 30000,
    img: 'img/guitar-4',
  },
  {
    id: 'DI192138',
    name: 'Dania Super',
    type: 'акустическая гитара',
    popularity: 5,
    stringNumber: 7,
    price: 3500,
    img: 'img/guitar-5',
  },
  {
    id: 'SO934345',
    name: 'Честер WX ',
    type: 'электрогитара',
    popularity: 17,
    stringNumber: 6,
    price: 15300,
    img: 'img/guitar-1',
  },
  {
    id: 'DI082347',
    name: 'Dania VX',
    type: 'укулеле',
    popularity: 5,
    stringNumber: 4,
    price: 2200,
    img: 'img/guitar-3',
  },
  {
    id: 'SO135646',
    name: 'Честер Plus',
    type: 'электрогитара',
    popularity: 27,
    stringNumber: 4,
    price: 30000,
    img: 'img/guitar-6',
  },
  {
    id: 'VO154751',
    name: 'Виолана 300',
    type: 'акустическая гитара',
    popularity: 3,
    stringNumber: 7,
    price: 1700,
    img: 'img/guitar-5',
  },
]
